### ISSUE TITLE
2. Debugging Playgrounds

### ISSUE THREAD

**Issue by 14m0ngZf3nc3** [MakeSchool-Tutorials/Intro-Getting-Started-With-Xcode-Playgrounds#2]
The live visualization is malfunctioning. This seems to be a known problem. How can we finish the lessons without proper tools??

**Comment by dionlarson** [comment]
The visualizations have mainly been a problem on the functions playground (second one). This caused issues on about 25% of computers and is being restructured for stability over the weekend.

Your instructors will be able to help you debug any problems there are with your system and the playgrounds when you arrive on Monday! :)
