### ISSUE TITLE
2. Debugging Playgrounds

### ISSUE THREAD

**Issue by jlratliff** [MakeSchool-Tutorials/Intro-Getting-Started-With-Xcode-Playgrounds#5]
The instructions mention a button marked 1 and a button marked 2 in this screenshot, but I don't see those numbers.
![screen shot 2016-11-18 at 5 06 09 pm](https://cloud.githubusercontent.com/assets/12715030/20426354/5e186b68-adb1-11e6-816e-15ab8be4890f.png)

**Comment by dionlarson** [comment]
See the section titled `Turning on line numbers`.
